package ui;
import java.awt.*;
import java.awt.event.*;

import business.ArmazemFacade;
import business.Robot;

import javax.swing.*;

public class AlterarRobotFrame extends javax.swing.JFrame {
    Robot robot;
    ArmazemFacade af;
    RobotFrame to_update;

    private void  atualizar_btnActionPerformed(ActionEvent e) {
        this.dispose();
        try {
            int id = Integer.parseInt(id_txt.getText());

            Robot tmp = new Robot();

            if (!(id == -1)) {
                if (!tmp.equals(robot)) {
                    this.af.alteraRobot(robot.getId());

                    List<Robot> list = this.af.getRobots();
                    this.to_update.updateTable(list);
                    this.to_update.updateList(list);

                    JOptionPane.showMessageDialog(new JFrame(), "Robot alterado com sucesso", "Robot alterado", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(new JFrame(), "Robot não sofreu alteração nenhuma.", "Robot inalterado", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
        } catch (Exception a) {
            JOptionPane.showMessageDialog(new JFrame(), "ERROR", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * Creates new form NovoRobotFrame
     */
    public AlterarRobotFrame(Robot r,ArmazemFacade af, RobotFrame f) {
        initComponents();0
        this.af = af;
        this.to_update=f;
        this.robot = r;
        this.id_txt.setText(String.valueOf(r.getId()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license
    private void initComponents() {
        atualizar_btn = new JButton();
        id_txt = new JLabel();
        label1 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Robot");
        Container contentPane = getContentPane();

        //---- atualizar_btn ----
        atualizar_btn.setText("Atualizar");
        atualizar_btn.addActionListener(e -> atualizar_btnActionPerformed(e));

        //---- id_txt ----
        id_txt.setText("Id");

        //---- label1 ----
        label1.setText("Id");
        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
                contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(label1)
                                                .addGap(6, 6, 6)
                                                .addComponent(id_txt, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addContainerGap(33, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                .addContainerGap(136, Short.MAX_VALUE)
                                .addComponent(atualizar_btn)
                                .addContainerGap()))));
        contentPaneLayout.setVerticalGroup(
                contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(label1))
                                        .addComponent(id_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(atualizar_btn)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        )));
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license
    private JButton atualizar_btn;
    private JLabel id_txt;
    private JLabel label1;
    // End of variables declaration//GEN-END:variables
}
    }
