package ui;
import java.awt.event.*;

import business.ArmazemFacade;
import business.Gestor;

import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.GroupLayout;

public class AlteraGestorFrame extends javax.swing.JFrame {
    Gestor gestor;
    ArmazemFrame af;
    GestorFrame to_update;

    private void atualizar_btnActionPerformed(ActionEvent e){
        this.dispose();
        try {
            String userName = this.user_txt.getText();
            String nome = this.nome_txt.getText();
            String email = this.email_txt.getText();

            Gestor temp = new Gestor(gestor.getUserName(), nome, email);
            if (!userName.equals("")){
                if(!temp.equals(gestor)){
                    this.af.alteraGestor(gestor.getUserName(), nome,email);

                    List<Gestor> list = this.af.getGestores();
                    this.to_update.updateTable(list);
                    this.to_update.updateList(list);
                JOptionPane.showMessageDialog(new JFrame(), "Gestor alterado com sucesso.","Gestor Alterado", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(new JFrame(), "Gestor não sofreu alterações", "Gestor Inalterado", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }

        }
        catch (Exception a){
            JOptionPane.showMessageDialog(new JFrame(), "Erro", "", JOptionPane.INFORMATION_MESSAGE);
        }

    }
    /**
     * Creates new form NovoClienteFrame
     */
    public AlteraGestorFrame(Gestor g, ArmazemFacade af, GestorFrame f) {
        initComponents();
        this.af = af;
        this.to_update=f;
        this.gestor = g;
        this.user_txt.setText(g.getUserName());
        this.nome_txt.setText(g.getNome());
        this.email_txt.setText(g.getEmail());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license
    private void initComponents() {
        atualizar_btn = new JButton();
        email_txt = new JTextField();
        label3 = new JLabel();
        label2 = new JLabel();
        user_txt = new JTextField();
        nome_txt = new JTextField();
        label1 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Gestor");
        Container contentPane = getContentPane();

        //---- atualizar_btn ----
        atualizar_btn.setText("Atualizar");
        atualizar_btn.addActionListener(e -> atualizar_btnActionPerformed(e));

        //---- label3 ----
        label3.setText("E-mail");

        //---- nome_txt ----
        nome_txt.setToolTipText("");
        nome_txt.setEditable(false);

        //---- label2 ----
        label1.setText("Nome");

        //---- label3 ----
        label3.setText("User Name");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
                contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(label1)
                                                .addGap(6, 6, 6)
                                                .addComponent(user_txt, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addComponent(label2)
                                                .addGap(6, 6, 6)
                                                .addComponent(nome_txt, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(label3)
                                                .addGap(6, 6, 6)
                                                .addComponent(email_txt, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(33, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                .addContainerGap(136, Short.MAX_VALUE)
                                .addComponent(atualizar_btn)
                                .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
                contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(label1))
                                        .addComponent(user_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(label2))
                                        .addComponent(nome_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(contentPaneLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(label3))
                                        .addComponent(email_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(atualizar_btn)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license
    private JButton atualizar_btn;
    private JTextField email_txt;
    private JLabel label3;
    private JLabel label2;
    private JTextField user_txt;
    private JTextField nome_txt;
    private JLabel label1;
    // End of variables declaration//GEN-END:variables
}


