package ui;
import business.gConta.Gestor;
import business.ArmazemFacade;
import java.awt.*;
import java.awt.event.*;
import java.util.Collection;
import java.util.List;
import javax.swing.*;
import javax.swing.GroupLayout;

public class NovoGestorFrame extends javax.swing.JFrame {
    ArmazemFacade af;
    GestorFrame to_update;
    //private Label password_txt; //----------------
    /* RegistaDescargaFrame to_update2;*/

    private void registar_btnActionPerformed(ActionEvent e) throws Exception {
        String userName = this.user_txt.getText();
        //String password = this.password_txt.getText();
        String nome = this.nome_txt.getText();
        String email = this.email_txt.getText();

            if (!userName.equals("") && !email.equals("")){
                this.af.registaGestor(userName,nome, email);

                Collection<Gestor> list = this.af.getGestores();
                if (to_update != null){
                    this.to_update.updateTable(list);
                    this.to_update.updateList((List<Gestor>) list);
                }

                JOptionPane.showMessageDialog(new JFrame(), "Gestor registado com sucesso", "Gestor Registado", JOptionPane.PLAIN_MESSAGE);
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(new JFrame(), "Preencha todos os campos.", "Campos por preencher", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
    }
    private void sair_btnActionPerformed(ActionEvent e) {
        this.dispose();
    }
    /**
     * Creates new form NovoClienteFrame
     */
    public NovoGestorFrame(ArmazemFacade af, GestorFrame f) {
        initComponents();
        this.af = af;
        this.to_update=f;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license

    private void initComponents() {
        user_txt = new JTextField();
        nome_txt = new JTextField();
        email_txt = new JTextField();
        registar_btn = new JButton();
        label1 = new JLabel();
        label2 = new JLabel();
        label3 = new JLabel();
        sair_btn = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Gestor");
        Container contentPane = getContentPane();
        //---- nome_txt ----
        user_txt.setToolTipText("");

        //---- registar_btn ----
        registar_btn.setText("Registar");
        registar_btn.addActionListener(e -> {
            try {
                registar_btnActionPerformed(e);
            } catch (Exception e1) {
                e1.printStackTrace();
            }
        });
        //---- label1 ----
        label1.setText("User Name");
        //---- label2 ----
        label2.setText("Nome");
        //---- label3 ----
        label3.setText("E-mail");

        //---- sair_btn ----
        sair_btn.setText("Sair");
        sair_btn.addActionListener(e -> sair_btnActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
                contentPaneLayout.createParallelGroup()
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sair_btn, GroupLayout.PREFERRED_SIZE, 53, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(registar_btn)
                                .addContainerGap())
                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(label2)
                                        .addComponent(label3)
                                        .addComponent(label1))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(user_txt)
                                        .addComponent(nome_txt)
                                        .addComponent(email_txt, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
                contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(nome_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label1))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(user_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label2))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(email_txt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label3))
                                .addGap(18, 18, 18)
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(registar_btn)
                                        .addComponent(sair_btn))
                                .addContainerGap())
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license
    private JTextField user_txt;
    private JTextField nome_txt;
    private JTextField email_txt;
    private JButton registar_btn;
    private JLabel label1;
    private JLabel label2;
    private JLabel label3;
    private JButton sair_btn;
    // End of variables declaration//GEN-END:variables
}
